// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repository

type EntityImageList struct {
	Service   string
	EntityID  string
	ImagePath string
	IsCover   bool
}

type EntityState struct {
	Service    string
	EntityID   string
	ImageCount int32
	Status     string
	MaxCount   int32
}

type ProductImageList struct {
	Service   string
	EntityID  string
	ImagePath string
	IsCover   bool
}

type ProductState struct {
	Service    string
	EntityID   string
	ImageCount int32
	Status     string
	MaxCount   int32
}

type UserImageList struct {
	Service   string
	EntityID  string
	ImagePath string
	IsCover   bool
}

type UserState struct {
	Service    string
	EntityID   string
	ImageCount int32
	Status     string
	MaxCount   int32
}
